name: lqmc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.11
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.2.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.7.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=2.2.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dm-tree=0.1.7
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.2
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gast=0.4.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-auth=2.29.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.54.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h5py=3.10.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.2
  - jax=0.4.25
  - jaxlib=0.4.23
  - jedi=0.18.1
  - jinja2=3.1.3
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libblas=3.9.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.6.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libgrpc=1.54.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.26
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=15.6
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - ml_dtypes=0.3.2
  - mpg123=1.32.4
  - multidict=6.0.5
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nccl=2.20.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.98
  - numexpr=2.8.7
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.2
  - openssl=3.2.1
  - opt-einsum=3.3.0
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=24.0
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.43.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.21.12
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.9
  - scipy=1.12.0
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tensorboard=2.12.3
  - tensorboard-data-server=0.7.0
  - tensorflow=2.12.1
  - tensorflow-base=2.12.1
  - tensorflow-estimator=2.12.1
  - tensorflow-gpu=2.12.1
  - tensorflow-probability=0.14.0
  - termcolor=2.4.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=3.0.1
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - wrapt=1.16.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - ucimlrepo==0.0.6
      - wget==3.2
